version: "23" # Adjust the version as needed

services:
  # Service: BITPING
  cash-mint_bitping:
    container_name: cash-mint_bitping
    image: bitping/bitpingd:latest
    restart: always
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/bitping:/root/.bitpingd
    entrypoint: >
      /bin/bash -c "
      /app/bitpingd login
      --email '${CFG_SERVICE_EMAIL}'
      --password '${CFG_SERVICE_PASSWORD}' &&
      /app/docker.sh"
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.3
    cpus: 0.1
    mem_limit: 50M

  # Service: EARNFM
  cash-mint_earnfm:
    container_name: cash-mint_earnfm
    image: earnfm/earnfm-client:latest
    restart: always
    environment:
      - EARNFM_TOKEN=${CFG_EARNFM_TOKEN}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.4
    cpus: 0.1
    mem_limit: 50M

  # Service: HONEYGAIN
  cash-mint_honeygain:
    container_name: cash-mint_honeygain
    image: honeygain/honeygain:latest
    restart: always
    command: >
      -email ${CFG_HG_EMAIL} 
      -pass ${CFG_HG_PASSWORD} 
      -device ${CFG_NODENAME}
      -tou-accept
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.5
    cpus: 0.1
    mem_limit: 50M

  # Service: PACKETSTREAM
  cash-mint_packetstream:
    container_name: cash-mint_packetstream
    image: packetstream/psclient:latest
    restart: always
    environment:
      - CID=${CFG_PACKETSTREAM_CID}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.6
    cpus: 0.1
    mem_limit: 50M

  # Service: PROXYLITE
  cash-mint_proxylite:
    container_name: cash-mint_proxylite
    image: proxylite/proxyservice:latest
    restart: always
    environment:
      - USER_ID=${CFG_PROXYLITE_ID}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.7
    cpus: 0.1
    mem_limit: 50M

  # Service: REPOCKET
  cash-mint_repocket:
    container_name: cash-mint_repocket-1
    image: repocket/repocket:latest
    restart: always
    environment:
      - RP_EMAIL=${CFG_SERVICE_EMAIL}
      - RP_API_KEY=${CFG_RP_API_KEY}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.8
    cpus: 0.1
    mem_limit: 50M

  # Service: PAWNS
  cash-mint_pawns:
    container_name: cash-mint_pawns
    image: iproyal/pawns-cli:latest
    restart: always
    command: >
      -email=${CFG_SERVICE_EMAIL} 
      -password=${CFG_SERVICE_PASSWORD} 
      -device-name=${CFG_NODENAME} 
      -accept-tos
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.9
    cpus: 0.1
    mem_limit: 50M

  # Service: PROXYRACK
  cash-mint_proxyrack:
    container_name: cash-mint_proxyrack
    image: proxyrack/pop:latest
    restart: always
    environment:
      - UUID=${CFG_UUID}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.10
    cpus: 0.1
    mem_limit: 50M

  # Service: TRAFFMONETIZER
  cash-mint_traffmonetizer:
    container_name: cash-mint_traffmonetizer
    image: traffmonetizer/cli_v2:latest
    restart: always
    command: >
      start 
      accept 
      --token ${CFG_TRAFFMONETIZER_TOKEN}
      --device-name ${CFG_NODENAME}
      status
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.11
    cpus: 0.1
    mem_limit: 50M

  # Service: SPEEDSHARE
  cash-mint_speedshare:
    container_name: cash-mint_speedshare
    image: mrcolorrain/speedshare
    restart: always
    hostname: ${CFG_NODENAME}
    environment:
            - CODE=${CFG_SPEEDSHARE_AUTH_CODE}
            - SPEEDSHARE_UUID=${CFG_UUID}
    platform: linux/amd64
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.12
    cpus: 0.1
    mem_limit: 50M

  # Service: GRASS
  cash-mint_grass:
    container_name: cash-mint_grass
    image: mrcolorrain/grass
    restart: always
    environment:
            - GRASS_USER=${CFG_SERVICE_EMAIL}
            - GRASS_PASS=$CFG_SERVICE_PASSWORD}
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.13
    cpus: 0.1
    mem_limit: 50M

  # Service: SPIDE
  cash-mint_spide:
    container_name: cash-mint_spide
    image: xterna/spide-network
    restart: always
    platform: linux/amd64
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.14
    cpus: 0.1
    mem_limit: 50M

  # Service: EARNAPP
  cash-mint_earnapp:
    container_name: cash-mint_earnapp
    image: madereddy/earnapp
    restart: always
    environment:
            - EARNAPP_UUID=${CFG_UUID}
            - EARNAPP_TERM=yes
    platform: linux/amd64
    volumes:
      - ${CFG_WORKING_DIRECTORY}/.appdata/earnapp:/root/.earnappd
    networks:
      cash-mint_network:
        ipv4_address: 20.20.0.15
    cpus: 0.1
    mem_limit: 50M


# network for cash-mint_* containers
networks:
  cash-mint_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 20.20.0.0/24
